version: '3'
services: 
  db:
    image: mysql:5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample_db
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes: 
      - ./mysql-datavolume:/var/lib/mysql
    ports: 
      - 3306:3306

